"""Kconfig helpers: chip fragment generation and the menuconfig launcher.

The SDK ships the Kconfig tree (``<sdk>/sdk/Kconfig``); the project-local
``.config`` is the single source of truth for firmware content since SDK
v0.2.2. stmtool provides the UX side: an interactive curses menuconfig
(``stmtool config``) over the tree, with the chip-derived fragment injected
the same way ``sdk/cmake/kconfig.cmake`` does at build time.
"""

import os
import subprocess
import sys
from pathlib import Path


def chip_kconfig_fragment(chip: str) -> str:
    """Render the generated Kconfig fragment for ``chip`` (e.g. STM32F407VG).

    Mirrors the fragment written by ``sdk/cmake/kconfig.cmake``: a family
    ``def_bool`` for future per-family ``depends on`` plus the chip name.
    """
    family = f"stm32{chip[5:7].lower()}"
    return (
        f"# Generated by stmtool from chip={chip} -- do not edit.\n"
        f"config STM32_FAMILY_{family.upper()}\n"
        "\tdef_bool y\n"
        "\n"
        "config STM32_CHIP_NAME\n"
        "\tstring\n"
        f'\tdefault "{chip}"\n'
    )


def run_menuconfig(sdk_root: Path, chip: str, project_dir: Path) -> int:
    """Open the kconfiglib menuconfig TUI for the project's ``.config``.

    Saving inside the TUI writes ``project_dir/.config``; opening a project
    without one starts from the tree defaults, so the same command doubles
    as the migration path for pre-v0.2.2 projects.
    """
    kconfig_root = sdk_root / "sdk" / "Kconfig"
    gen_dir = project_dir / "out" / "generated"
    gen_dir.mkdir(parents=True, exist_ok=True)
    fragment = gen_dir / "Kconfig.chip"
    fragment.write_text(chip_kconfig_fragment(chip))

    env = os.environ.copy()
    env["srctree"] = str(sdk_root / "sdk")
    env["KCONFIG_CONFIG"] = str(project_dir / ".config")
    env["STM32_KCONFIG_CHIP_FRAGMENT"] = str(fragment)

    result = subprocess.run(
        [sys.executable, "-m", "menuconfig", str(kconfig_root)],
        env=env,
        check=False,
    )
    return result.returncode
